version: '3'
services:
  app:
    build:
      context: .

# =========ローカルと本番切り替え===========
    command: bundle exec puma -C config/puma.rb -e production
    # command: bundle exec puma -C config/puma.rb
# =========ローカルと本番切り替え===========

    volumes: 
      - .:/with_nurse
      - public-data:/with_nurse/public
      - tmp-data:/with_nurse/tmp
      - log-data:/with_nurse/log
    networks: 
      - with_nurse-network

    #=========ローカル用================
  #   depends_on: 
  #     - db
  # db:
  #   image: mysql:8.0
  #   environment:
  #     MYSQL_USERNAME: root
  #     MYSQL_ROOT_PASSWORD: password
  #   ports:
  #     - '3306:3306'
  #   command: --default-authentication-plugin=mysql_native_password
  #   volumes:
  #     - db-data:/var/lib/mysql
  #   networks: 
  #     - with_nurse-network
    #=========ローカル用================

  web:
    build: 
      context: ./nginx_docker
    # command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - public-data:/with_nurse/public
      - tmp-data:/with_nurse/tmp
    ports:
      - "80:80"
    depends_on:
      - app
      - chrome 
    networks: 
      - with_nurse-network
    stdin_open: true
    tty: true
  chrome:
    image: selenium/standalone-chrome:latest
    ports:
      - 4444:4444

volumes:
  public-data:
  tmp-data:
  log-data:
  db-data:
  # mysql-data:
  #   driver: local

networks:
  with_nurse-network:
    external: true
